// entityclass.c -- classname -> entity-factory dispatch for the statically
// linked game DLL.  On Win32 GetDispatch resolves entity factories with
// GetProcAddress; the Dreamcast links halflife statically, so the factories
// generated by LINK_ENTITY_TO_CLASS are collected in one table here instead.

#include "quakedef.h"
#include "pr_dlls.h"

struct entvars_s;

extern void spark_shower( struct entvars_s *pev );
extern void env_explosion( struct entvars_s *pev );
extern void monster_flyer( struct entvars_s *pev );
extern void monster_flyer_flock( struct entvars_s *pev );
extern void monster_alien_grunt( struct entvars_s *pev );
extern void item_airtank( struct entvars_s *pev );
extern void monster_apache( struct entvars_s *pev );
extern void hvr_rocket( struct entvars_s *pev );
extern void monster_barnacle( struct entvars_s *pev );
extern void monster_barney( struct entvars_s *pev );
extern void monster_barney_dead( struct entvars_s *pev );
extern void info_bigmomma( struct entvars_s *pev );
extern void bmortar( struct entvars_s *pev );
extern void monster_bigmomma( struct entvars_s *pev );
extern void monster_bloater( struct entvars_s *pev );
extern void func_wall( struct entvars_s *pev );
extern void func_wall_toggle( struct entvars_s *pev );
extern void func_conveyor( struct entvars_s *pev );
extern void func_illusionary( struct entvars_s *pev );
extern void func_monsterclip( struct entvars_s *pev );
extern void func_rotating( struct entvars_s *pev );
extern void func_pendulum( struct entvars_s *pev );
extern void squidspit( struct entvars_s *pev );
extern void monster_bullchicken( struct entvars_s *pev );
extern void env_global( struct entvars_s *pev );
extern void multisource( struct entvars_s *pev );
extern void func_button( struct entvars_s *pev );
extern void func_rot_button( struct entvars_s *pev );
extern void momentary_rot_button( struct entvars_s *pev );
extern void env_spark( struct entvars_s *pev );
extern void env_debris( struct entvars_s *pev );
extern void button_target( struct entvars_s *pev );
extern void monster_alien_controller( struct entvars_s *pev );
extern void controller_head_ball( struct entvars_s *pev );
extern void controller_energy_ball( struct entvars_s *pev );
extern void crossbow_bolt( struct entvars_s *pev );
extern void weapon_crossbow( struct entvars_s *pev );
extern void ammo_crossbow( struct entvars_s *pev );
extern void weapon_crowbar( struct entvars_s *pev );
extern void func_door( struct entvars_s *pev );
extern void func_water( struct entvars_s *pev );
extern void func_door_rotating( struct entvars_s *pev );
extern void momentary_door( struct entvars_s *pev );
extern void info_target( struct entvars_s *pev );
extern void env_bubbles( struct entvars_s *pev );
extern void beam( struct entvars_s *pev );
extern void env_lightning( struct entvars_s *pev );
extern void env_beam( struct entvars_s *pev );
extern void env_laser( struct entvars_s *pev );
extern void env_glow( struct entvars_s *pev );
extern void env_sprite( struct entvars_s *pev );
extern void gibshooter( struct entvars_s *pev );
extern void env_shooter( struct entvars_s *pev );
extern void test_effect( struct entvars_s *pev );
extern void env_blood( struct entvars_s *pev );
extern void env_shake( struct entvars_s *pev );
extern void env_fade( struct entvars_s *pev );
extern void env_message( struct entvars_s *pev );
extern void env_funnel( struct entvars_s *pev );
extern void env_beverage( struct entvars_s *pev );
extern void item_sodacan( struct entvars_s *pev );
extern void weapon_egon( struct entvars_s *pev );
extern void ammo_egonclip( struct entvars_s *pev );
extern void func_breakable( struct entvars_s *pev );
extern void func_pushable( struct entvars_s *pev );
extern void func_tank( struct entvars_s *pev );
extern void func_tanklaser( struct entvars_s *pev );
extern void func_tankrocket( struct entvars_s *pev );
extern void func_tankmortar( struct entvars_s *pev );
extern void func_tankcontrols( struct entvars_s *pev );
extern void streak_spiral( struct entvars_s *pev );
extern void garg_stomp( struct entvars_s *pev );
extern void monster_gargantua( struct entvars_s *pev );
extern void env_smoker( struct entvars_s *pev );
extern void weapon_gauss( struct entvars_s *pev );
extern void ammo_gaussclip( struct entvars_s *pev );
extern void monster_generic( struct entvars_s *pev );
extern void grenade( struct entvars_s *pev );
extern void weapon_glock( struct entvars_s *pev );
extern void weapon_9mmhandgun( struct entvars_s *pev );
extern void ammo_glockclip( struct entvars_s *pev );
extern void ammo_9mmclip( struct entvars_s *pev );
extern void monster_gman( struct entvars_s *pev );
extern void func_recharge( struct entvars_s *pev );
extern void monster_cine_scientist( struct entvars_s *pev );
extern void monster_cine_panther( struct entvars_s *pev );
extern void monster_cine_barney( struct entvars_s *pev );
extern void monster_cine2_scientist( struct entvars_s *pev );
extern void monster_cine2_hvyweapons( struct entvars_s *pev );
extern void monster_cine2_slave( struct entvars_s *pev );
extern void monster_cine3_scientist( struct entvars_s *pev );
extern void monster_cine3_barney( struct entvars_s *pev );
extern void cine_blood( struct entvars_s *pev );
extern void cycler( struct entvars_s *pev );
extern void cycler_prdroid( struct entvars_s *pev );
extern void cycler_sprite( struct entvars_s *pev );
extern void cycler_weapon( struct entvars_s *pev );
extern void cycler_wreckage( struct entvars_s *pev );
extern void weapon_handgrenade( struct entvars_s *pev );
extern void monster_human_assassin( struct entvars_s *pev );
extern void monster_headcrab( struct entvars_s *pev );
extern void monster_babycrab( struct entvars_s *pev );
extern void item_healthkit( struct entvars_s *pev );
extern void func_healthcharger( struct entvars_s *pev );
extern void monster_human_grunt( struct entvars_s *pev );
extern void monster_grunt_repel( struct entvars_s *pev );
extern void monster_hgrunt_dead( struct entvars_s *pev );
extern void hornet( struct entvars_s *pev );
extern void weapon_hornetgun( struct entvars_s *pev );
extern void monster_houndeye( struct entvars_s *pev );
extern void monster_ichthyosaur( struct entvars_s *pev );
extern void monster_alien_slave( struct entvars_s *pev );
extern void monster_vortigaunt( struct entvars_s *pev );
extern void world_items( struct entvars_s *pev );
extern void item_suit( struct entvars_s *pev );
extern void item_battery( struct entvars_s *pev );
extern void item_antidote( struct entvars_s *pev );
extern void item_security( struct entvars_s *pev );
extern void item_longjump( struct entvars_s *pev );
extern void monster_leech( struct entvars_s *pev );
extern void light( struct entvars_s *pev );
extern void light_spot( struct entvars_s *pev );
extern void light_environment( struct entvars_s *pev );
extern void game_text( struct entvars_s *pev );
extern void game_team_master( struct entvars_s *pev );
extern void game_team_set( struct entvars_s *pev );
extern void game_zone_player( struct entvars_s *pev );
extern void game_player_hurt( struct entvars_s *pev );
extern void game_counter( struct entvars_s *pev );
extern void game_counter_set( struct entvars_s *pev );
extern void game_player_equip( struct entvars_s *pev );
extern void game_player_team( struct entvars_s *pev );
extern void monstermaker( struct entvars_s *pev );
extern void func_mortar_field( struct entvars_s *pev );
extern void monster_mortar( struct entvars_s *pev );
extern void weapon_mp5( struct entvars_s *pev );
extern void weapon_9mmAR( struct entvars_s *pev );
extern void ammo_mp5clip( struct entvars_s *pev );
extern void ammo_9mmAR( struct entvars_s *pev );
extern void ammo_9mmbox( struct entvars_s *pev );
extern void ammo_mp5grenades( struct entvars_s *pev );
extern void ammo_ARgrenades( struct entvars_s *pev );
extern void monster_nihilanth( struct entvars_s *pev );
extern void nihilanth_energy_ball( struct entvars_s *pev );
extern void info_node( struct entvars_s *pev );
extern void info_node_air( struct entvars_s *pev );
extern void node_viewer( struct entvars_s *pev );
extern void node_viewer_human( struct entvars_s *pev );
extern void node_viewer_fly( struct entvars_s *pev );
extern void node_viewer_large( struct entvars_s *pev );
extern void monster_osprey( struct entvars_s *pev );
extern void path_corner( struct entvars_s *pev );
extern void path_track( struct entvars_s *pev );
extern void func_plat( struct entvars_s *pev );
extern void func_platrot( struct entvars_s *pev );
extern void func_train( struct entvars_s *pev );
extern void func_tracktrain( struct entvars_s *pev );
extern void func_traincontrols( struct entvars_s *pev );
extern void func_trackchange( struct entvars_s *pev );
extern void func_trackautochange( struct entvars_s *pev );
extern void func_guntarget( struct entvars_s *pev );
extern void player( struct entvars_s *pev );
extern void monster_hevsuit_dead( struct entvars_s *pev );
extern void player_weaponstrip( struct entvars_s *pev );
extern void player_loadsaved( struct entvars_s *pev );
extern void info_intermission( struct entvars_s *pev );
extern void monster_player( struct entvars_s *pev );
extern void weapon_python( struct entvars_s *pev );
extern void weapon_357( struct entvars_s *pev );
extern void ammo_357( struct entvars_s *pev );
extern void monster_rat( struct entvars_s *pev );
extern void monster_cockroach( struct entvars_s *pev );
extern void laser_spot( struct entvars_s *pev );
extern void weapon_rpg( struct entvars_s *pev );
extern void rpg_rocket( struct entvars_s *pev );
extern void ammo_rpgclip( struct entvars_s *pev );
extern void monster_satchel( struct entvars_s *pev );
extern void weapon_satchel( struct entvars_s *pev );
extern void monster_scientist( struct entvars_s *pev );
extern void monster_scientist_dead( struct entvars_s *pev );
extern void monster_sitting_scientist( struct entvars_s *pev );
extern void scripted_sequence( struct entvars_s *pev );
extern void aiscripted_sequence( struct entvars_s *pev );
extern void scripted_sentence( struct entvars_s *pev );
extern void monster_furniture( struct entvars_s *pev );
extern void weapon_shotgun( struct entvars_s *pev );
extern void ammo_buckshot( struct entvars_s *pev );
extern void ambient_generic( struct entvars_s *pev );
extern void env_sound( struct entvars_s *pev );
extern void speaker( struct entvars_s *pev );
extern void soundent( struct entvars_s *pev );
extern void monster_snark( struct entvars_s *pev );
extern void weapon_snark( struct entvars_s *pev );
extern void info_null( struct entvars_s *pev );
extern void info_player_deathmatch( struct entvars_s *pev );
extern void info_player_start( struct entvars_s *pev );
extern void info_landmark( struct entvars_s *pev );
extern void DelayedUse( struct entvars_s *pev );
extern void monster_tentacle( struct entvars_s *pev );
extern void monster_tentaclemaw( struct entvars_s *pev );
extern void func_friction( struct entvars_s *pev );
extern void trigger_auto( struct entvars_s *pev );
extern void trigger_relay( struct entvars_s *pev );
extern void multi_manager( struct entvars_s *pev );
extern void env_render( struct entvars_s *pev );
extern void trigger( struct entvars_s *pev );
extern void trigger_hurt( struct entvars_s *pev );
extern void trigger_monsterjump( struct entvars_s *pev );
extern void trigger_cdaudio( struct entvars_s *pev );
extern void target_cdaudio( struct entvars_s *pev );
extern void trigger_multiple( struct entvars_s *pev );
extern void trigger_once( struct entvars_s *pev );
extern void trigger_counter( struct entvars_s *pev );
extern void trigger_transition( struct entvars_s *pev );
extern void fireanddie( struct entvars_s *pev );
extern void trigger_changelevel( struct entvars_s *pev );
extern void func_ladder( struct entvars_s *pev );
extern void trigger_push( struct entvars_s *pev );
extern void trigger_teleport( struct entvars_s *pev );
extern void info_teleport_destination( struct entvars_s *pev );
extern void trigger_autosave( struct entvars_s *pev );
extern void trigger_endsection( struct entvars_s *pev );
extern void trigger_gravity( struct entvars_s *pev );
extern void trigger_changetarget( struct entvars_s *pev );
extern void trigger_camera( struct entvars_s *pev );
extern void monster_tripmine( struct entvars_s *pev );
extern void weapon_tripmine( struct entvars_s *pev );
extern void monster_turret( struct entvars_s *pev );
extern void monster_miniturret( struct entvars_s *pev );
extern void monster_sentry( struct entvars_s *pev );
extern void weaponbox( struct entvars_s *pev );
extern void infodecal( struct entvars_s *pev );
extern void bodyque( struct entvars_s *pev );
extern void worldspawn( struct entvars_s *pev );
extern void xen_plantlight( struct entvars_s *pev );
extern void xen_hair( struct entvars_s *pev );
extern void xen_ttrigger( struct entvars_s *pev );
extern void xen_tree( struct entvars_s *pev );
extern void xen_spore_small( struct entvars_s *pev );
extern void xen_spore_medium( struct entvars_s *pev );
extern void xen_spore_large( struct entvars_s *pev );
extern void xen_hull( struct entvars_s *pev );
extern void monster_zombie( struct entvars_s *pev );
extern void monster_rosenberg( struct entvars_s *pev );
extern void env_warpball( struct entvars_s *pev );
extern void item_helmet( struct entvars_s *pev );
extern void item_armorvest( struct entvars_s *pev );
extern void trigger_playerfreeze( struct entvars_s *pev );

typedef struct
{
	char       *pClassName;
	ENTITYINIT  pFactory;
} dispatch_entry_t;

static dispatch_entry_t gEntityDispatch[] =
{
	{ "spark_shower", spark_shower },
	{ "env_explosion", env_explosion },
	{ "monster_flyer", monster_flyer },
	{ "monster_flyer_flock", monster_flyer_flock },
	{ "monster_alien_grunt", monster_alien_grunt },
	{ "item_airtank", item_airtank },
	{ "monster_apache", monster_apache },
	{ "hvr_rocket", hvr_rocket },
	{ "monster_barnacle", monster_barnacle },
	{ "monster_barney", monster_barney },
	{ "monster_barney_dead", monster_barney_dead },
	{ "info_bigmomma", info_bigmomma },
	{ "bmortar", bmortar },
	{ "monster_bigmomma", monster_bigmomma },
	{ "monster_bloater", monster_bloater },
	{ "func_wall", func_wall },
	{ "func_wall_toggle", func_wall_toggle },
	{ "func_conveyor", func_conveyor },
	{ "func_illusionary", func_illusionary },
	{ "func_monsterclip", func_monsterclip },
	{ "func_rotating", func_rotating },
	{ "func_pendulum", func_pendulum },
	{ "squidspit", squidspit },
	{ "monster_bullchicken", monster_bullchicken },
	{ "env_global", env_global },
	{ "multisource", multisource },
	{ "func_button", func_button },
	{ "func_rot_button", func_rot_button },
	{ "momentary_rot_button", momentary_rot_button },
	{ "env_spark", env_spark },
	{ "env_debris", env_debris },
	{ "button_target", button_target },
	{ "monster_alien_controller", monster_alien_controller },
	{ "controller_head_ball", controller_head_ball },
	{ "controller_energy_ball", controller_energy_ball },
	{ "crossbow_bolt", crossbow_bolt },
	{ "weapon_crossbow", weapon_crossbow },
	{ "ammo_crossbow", ammo_crossbow },
	{ "weapon_crowbar", weapon_crowbar },
	{ "func_door", func_door },
	{ "func_water", func_water },
	{ "func_door_rotating", func_door_rotating },
	{ "momentary_door", momentary_door },
	{ "info_target", info_target },
	{ "env_bubbles", env_bubbles },
	{ "beam", beam },
	{ "env_lightning", env_lightning },
	{ "env_beam", env_beam },
	{ "env_laser", env_laser },
	{ "env_glow", env_glow },
	{ "env_sprite", env_sprite },
	{ "gibshooter", gibshooter },
	{ "env_shooter", env_shooter },
	{ "test_effect", test_effect },
	{ "env_blood", env_blood },
	{ "env_shake", env_shake },
	{ "env_fade", env_fade },
	{ "env_message", env_message },
	{ "env_funnel", env_funnel },
	{ "env_beverage", env_beverage },
	{ "item_sodacan", item_sodacan },
	{ "weapon_egon", weapon_egon },
	{ "ammo_egonclip", ammo_egonclip },
	{ "func_breakable", func_breakable },
	{ "func_pushable", func_pushable },
	{ "func_tank", func_tank },
	{ "func_tanklaser", func_tanklaser },
	{ "func_tankrocket", func_tankrocket },
	{ "func_tankmortar", func_tankmortar },
	{ "func_tankcontrols", func_tankcontrols },
	{ "streak_spiral", streak_spiral },
	{ "garg_stomp", garg_stomp },
	{ "monster_gargantua", monster_gargantua },
	{ "env_smoker", env_smoker },
	{ "weapon_gauss", weapon_gauss },
	{ "ammo_gaussclip", ammo_gaussclip },
	{ "monster_generic", monster_generic },
	{ "grenade", grenade },
	{ "weapon_glock", weapon_glock },
	{ "weapon_9mmhandgun", weapon_9mmhandgun },
	{ "ammo_glockclip", ammo_glockclip },
	{ "ammo_9mmclip", ammo_9mmclip },
	{ "monster_gman", monster_gman },
	{ "func_recharge", func_recharge },
	{ "monster_cine_scientist", monster_cine_scientist },
	{ "monster_cine_panther", monster_cine_panther },
	{ "monster_cine_barney", monster_cine_barney },
	{ "monster_cine2_scientist", monster_cine2_scientist },
	{ "monster_cine2_hvyweapons", monster_cine2_hvyweapons },
	{ "monster_cine2_slave", monster_cine2_slave },
	{ "monster_cine3_scientist", monster_cine3_scientist },
	{ "monster_cine3_barney", monster_cine3_barney },
	{ "cine_blood", cine_blood },
	{ "cycler", cycler },
	{ "cycler_prdroid", cycler_prdroid },
	{ "cycler_sprite", cycler_sprite },
	{ "cycler_weapon", cycler_weapon },
	{ "cycler_wreckage", cycler_wreckage },
	{ "weapon_handgrenade", weapon_handgrenade },
	{ "monster_human_assassin", monster_human_assassin },
	{ "monster_headcrab", monster_headcrab },
	{ "monster_babycrab", monster_babycrab },
	{ "item_healthkit", item_healthkit },
	{ "func_healthcharger", func_healthcharger },
	{ "monster_human_grunt", monster_human_grunt },
	{ "monster_grunt_repel", monster_grunt_repel },
	{ "monster_hgrunt_dead", monster_hgrunt_dead },
	{ "hornet", hornet },
	{ "weapon_hornetgun", weapon_hornetgun },
	{ "monster_houndeye", monster_houndeye },
	{ "monster_ichthyosaur", monster_ichthyosaur },
	{ "monster_alien_slave", monster_alien_slave },
	{ "monster_vortigaunt", monster_vortigaunt },
	{ "world_items", world_items },
	{ "item_suit", item_suit },
	{ "item_battery", item_battery },
	{ "item_antidote", item_antidote },
	{ "item_security", item_security },
	{ "item_longjump", item_longjump },
	{ "monster_leech", monster_leech },
	{ "light", light },
	{ "light_spot", light_spot },
	{ "light_environment", light_environment },
	{ "game_text", game_text },
	{ "game_team_master", game_team_master },
	{ "game_team_set", game_team_set },
	{ "game_zone_player", game_zone_player },
	{ "game_player_hurt", game_player_hurt },
	{ "game_counter", game_counter },
	{ "game_counter_set", game_counter_set },
	{ "game_player_equip", game_player_equip },
	{ "game_player_team", game_player_team },
	{ "monstermaker", monstermaker },
	{ "func_mortar_field", func_mortar_field },
	{ "monster_mortar", monster_mortar },
	{ "weapon_mp5", weapon_mp5 },
	{ "weapon_9mmAR", weapon_9mmAR },
	{ "ammo_mp5clip", ammo_mp5clip },
	{ "ammo_9mmAR", ammo_9mmAR },
	{ "ammo_9mmbox", ammo_9mmbox },
	{ "ammo_mp5grenades", ammo_mp5grenades },
	{ "ammo_ARgrenades", ammo_ARgrenades },
	{ "monster_nihilanth", monster_nihilanth },
	{ "nihilanth_energy_ball", nihilanth_energy_ball },
	{ "info_node", info_node },
	{ "info_node_air", info_node_air },
	{ "node_viewer", node_viewer },
	{ "node_viewer_human", node_viewer_human },
	{ "node_viewer_fly", node_viewer_fly },
	{ "node_viewer_large", node_viewer_large },
	{ "monster_osprey", monster_osprey },
	{ "path_corner", path_corner },
	{ "path_track", path_track },
	{ "func_plat", func_plat },
	{ "func_platrot", func_platrot },
	{ "func_train", func_train },
	{ "func_tracktrain", func_tracktrain },
	{ "func_traincontrols", func_traincontrols },
	{ "func_trackchange", func_trackchange },
	{ "func_trackautochange", func_trackautochange },
	{ "func_guntarget", func_guntarget },
	{ "player", player },
	{ "monster_hevsuit_dead", monster_hevsuit_dead },
	{ "player_weaponstrip", player_weaponstrip },
	{ "player_loadsaved", player_loadsaved },
	{ "info_intermission", info_intermission },
	{ "monster_player", monster_player },
	{ "weapon_python", weapon_python },
	{ "weapon_357", weapon_357 },
	{ "ammo_357", ammo_357 },
	{ "monster_rat", monster_rat },
	{ "monster_cockroach", monster_cockroach },
	{ "laser_spot", laser_spot },
	{ "weapon_rpg", weapon_rpg },
	{ "rpg_rocket", rpg_rocket },
	{ "ammo_rpgclip", ammo_rpgclip },
	{ "monster_satchel", monster_satchel },
	{ "weapon_satchel", weapon_satchel },
	{ "monster_scientist", monster_scientist },
	{ "monster_scientist_dead", monster_scientist_dead },
	{ "monster_sitting_scientist", monster_sitting_scientist },
	{ "scripted_sequence", scripted_sequence },
	{ "aiscripted_sequence", aiscripted_sequence },
	{ "scripted_sentence", scripted_sentence },
	{ "monster_furniture", monster_furniture },
	{ "weapon_shotgun", weapon_shotgun },
	{ "ammo_buckshot", ammo_buckshot },
	{ "ambient_generic", ambient_generic },
	{ "env_sound", env_sound },
	{ "speaker", speaker },
	{ "soundent", soundent },
	{ "monster_snark", monster_snark },
	{ "weapon_snark", weapon_snark },
	{ "info_null", info_null },
	{ "info_player_deathmatch", info_player_deathmatch },
	{ "info_player_start", info_player_start },
	{ "info_landmark", info_landmark },
	{ "DelayedUse", DelayedUse },
	{ "monster_tentacle", monster_tentacle },
	{ "monster_tentaclemaw", monster_tentaclemaw },
	{ "func_friction", func_friction },
	{ "trigger_auto", trigger_auto },
	{ "trigger_relay", trigger_relay },
	{ "multi_manager", multi_manager },
	{ "env_render", env_render },
	{ "trigger", trigger },
	{ "trigger_hurt", trigger_hurt },
	{ "trigger_monsterjump", trigger_monsterjump },
	{ "trigger_cdaudio", trigger_cdaudio },
	{ "target_cdaudio", target_cdaudio },
	{ "trigger_multiple", trigger_multiple },
	{ "trigger_once", trigger_once },
	{ "trigger_counter", trigger_counter },
	{ "trigger_transition", trigger_transition },
	{ "fireanddie", fireanddie },
	{ "trigger_changelevel", trigger_changelevel },
	{ "func_ladder", func_ladder },
	{ "trigger_push", trigger_push },
	{ "trigger_teleport", trigger_teleport },
	{ "info_teleport_destination", info_teleport_destination },
	{ "trigger_autosave", trigger_autosave },
	{ "trigger_endsection", trigger_endsection },
	{ "trigger_gravity", trigger_gravity },
	{ "trigger_changetarget", trigger_changetarget },
	{ "trigger_camera", trigger_camera },
	{ "monster_tripmine", monster_tripmine },
	{ "weapon_tripmine", weapon_tripmine },
	{ "monster_turret", monster_turret },
	{ "monster_miniturret", monster_miniturret },
	{ "monster_sentry", monster_sentry },
	{ "weaponbox", weaponbox },
	{ "infodecal", infodecal },
	{ "bodyque", bodyque },
	{ "worldspawn", worldspawn },
	{ "xen_plantlight", xen_plantlight },
	{ "xen_hair", xen_hair },
	{ "xen_ttrigger", xen_ttrigger },
	{ "xen_tree", xen_tree },
	{ "xen_spore_small", xen_spore_small },
	{ "xen_spore_medium", xen_spore_medium },
	{ "xen_spore_large", xen_spore_large },
	{ "xen_hull", xen_hull },
	{ "monster_zombie", monster_zombie },
	{ "monster_rosenberg", monster_rosenberg },
	{ "env_warpball", env_warpball },
	{ "item_helmet", item_helmet },
	{ "item_armorvest", item_armorvest },
	{ "trigger_playerfreeze", trigger_playerfreeze },
};

#define NUM_DISPATCH ( (int)( sizeof(gEntityDispatch) / sizeof(gEntityDispatch[0]) ) )

DISPATCHFUNCTION GetDispatch( char *pname )
{
	int  i;
	char szError[1024];

	for (i = 0; i < 248; i++)
	{
		if (!strcmp(pname, gEntityDispatch[i].pClassName))
			return (DISPATCHFUNCTION)gEntityDispatch[i].pFactory;
	}

	sprintf(szError, "GetDispatch failed for classname '%s'; try adding an entry to the table in %s at around line %d.", pname, __FILE__, __LINE__);
	return NULL;
}
