// sys.h -- non-portable functions

#ifdef __cplusplus
extern "C" {
#endif

//
// file IO
//

// returns the file size
// return -1 if file is not present
// the file should be in BINARY mode for stupid OSs that care
int Sys_FileOpenRead( char* path, int* pHandle, int bRegisterAsync );

FILE* Sys_FOpenReadSeek( const char* path, int offset );
int Sys_FileOpenWrite( char* path );
void Sys_FileClose( int hFile );
void Sys_FileSeek( int hFile, int position );
int Sys_FileRead( int hFile, void* dest, int count );
int Sys_FileWrite( int handle, void* data, int count );
int	Sys_FileTime( char* path );
void Sys_mkdir( char* path );
int Sys_FileTell( int i );

//
// Dreamcast / WinCE asynchronous file helpers.
//
struct _OVERLAPPED;
qboolean Sys_AsyncBusy( int id, struct _OVERLAPPED* pov );
int      Sys_FileReadAsync( void* hFile, void* buffer, int count, struct _OVERLAPPED* pov );

//
// memory protection
//
void Sys_MakeCodeWriteable( unsigned long startaddr, unsigned long length );

void Sys_Error( char* error, ... );
// an error will cause the entire program to exit

void Sys_ErrorColor( int wColor, char* fmt, ... );
// like Sys_Error, but paints the fatal screen in the given color

void Sys_Printf( char* fmt, ... );
// send text to the console

void Sys_Quit( void );

void Sys_Init( void );

DLL_EXPORT float Sys_FloatTime( void );

void Sys_SendKeyEvents( void );
// Perform Key_Event () callbacks until the input que is empty

void AlertMessage( ALERT_TYPE atype, char* szFmt, ... );

// Returns functions to dispatch events to entities (entityclass.c static table)
DISPATCHFUNCTION GetDispatch( char* pname );

// Returns entity initialization functions, generated by LINK_ENTITY_TO_CLASS
ENTITYINIT GetEntityInit( char* pClassName );

// Loads Server DLL
// szDllFilename - File name of dll to load
void LoadThisDll( char* szDllFilename );

// Export registry for save/restore function-pointer fixup (cbase.cpp)
char* NameForFunction( uint32 function );
uint32 FunctionFromName( char* pName );
void GameDLL_RegisterModules( void );

typedef long LONG;

void Sys_LowFPPrecision( void );
void Sys_HighFPPrecision( void );
void Sys_SetFPCW( void );

extern qboolean	g_bInStartup;
extern qboolean	g_bInactive;

extern qboolean	gfUseLANAuthentication;

extern qboolean gfBackground;

extern int giActive;
extern int giStateInfo;
extern short giSubState;	// 16-bit in the DC binary (Dispatch_Substate does a mov.w store)

extern void	(VID_Update)( struct vrect_s* rects );
extern void	(VID_Shutdown)( void );

void CDAudio_Play( int track, int looping );
void CDAudio_Pause( void );
void CDAudio_Resume( void );
void CDAudio_Update( void );

#ifdef __cplusplus
}
#endif

